name: Backend-Test

'on':
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Back end chai tests'
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Run All Node.js Tests
        run: npm run-script test